name: Grass Greener

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: otosakael/Greener
        token: ${{ secrets.GITHUB_TOKEN }}   # Menambahkan token autentikasi
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
        submodules: false
        set-safe-directory: true
    - run: date > date.txt
    - run: git config user.name "otosakael"
    - run: git config user.email "fachry2710@gmail.com"
    - run: git add date.txt
    - run: git commit -m 'Greening'
    - run: git push origin main
