name: Grass Greener

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: otosakael/Greener
        token: ${{ secrets.GITHUB_TOKEN }}   # Menambahkan token autentikasi
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
        submodules: false
        set-safe-directory: true
    - run: |
        git config --global user.name "otosakael"
        git config --global user.email "fachry2710@gmail.com"
        git config --global credential.helper 'cache --timeout=3600'
        echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
        git add date.txt
        git commit -m 'Greening'
        git push origin main
